AllCops:
  TargetRubyVersion: 2.6.2
  TargetRailsVersion: 5.2.3
  Exclude:
    - config.ru
    - Capfile
    - Gemfile
    - Guardfile
    - Rakefile
    - config/**/*
    - node_modules/**/*
    - db/**/*
    - bin/**/*
    - vendor/**/*

Rails:
  Enabled: true

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/BlockDelimiters:
  EnforcedStyle: semantic
  Exclude:
    - 'spec/**/*'

Metrics/LineLength:
  Max: 136

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Style/ClassAndModuleChildren:
  Enabled: false

Style/MutableConstant:
  Exclude:
    - 'app/assets/javascripts/**/*'
