version: 2.1

orbs:
  ruby-orbs: sue445/ruby-orbs@1.4.3

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.2-node-browsers
    steps:
      - checkout
      - ruby-orbs/bundle-install
      - run:
          name: Setup Database
          command: bin/rails db:create db:schema:load db:migrate
      - run:
          name: RSpec
          command: bundle exec rspec
